##########################################################################
## File: 02_Exp1_sample_information.R
## This script gives an overview of the sample demographics in Exp 2
# author: Christine Nussbaum
# date 03/2026


# clear directory
rm(list=ls())

#set working directory to current file
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))


# load required packages
library("tidyverse")

# load relevant functions
source("functions/mySummary.R") 

#---------------------------------------------------------------------------------
#get the preprocessed data: 

#S data
load(file="input/Exp2_Survey.RData")


## Meaning of Variables

## Meaning of Variables

#participant                    #individual participant code, generated by the system
#LAge                           #participants' age
#LSex                           #participants' sex: 1= female, 2 = male, 3 = diverse
#LMotherLanguage                #mother tongue, 1 = German, 2 = English, 3 = other
#LStudyWork                     #profession or study subject 
#LHearingKown                   #Hearing impairment? 1 = no, 2 = yes, 3 = don't know
#LHearingKind                   #in case of hearing impairment -> which kind
#LHearingImp                    #in case of hearing impairment -> degree of hearing impairment (1 = no impairment, 4 = extreme impairment)
#afterExp1AllSoundsPlayed_1     #were all sounds played after the experiment? 1 = yes, 2 = no, 3 = don't know
#InstructionsClear              #were all instructions clear in the experiment?            
#Eval1 - Eval8                  #8 questions about self-rated voice abilities and commitment to the Experiment  (see below)
#Strategy                       #did participants use a particular strategy during the task? (voluntary free-text field)
#Anmerkungen                    #any remarks about the experiment? (voluntary free-text field)
#TIME_total                     #total time of the experiment
#VPN_Code                       #individual participant code, self-generated



#------------------------------------------------------------------------------------------------------------------#
#                                           Sample Demographics                                                    #
#------------------------------------------------------------------------------------------------------------------#

#general demographics
Age <- mySummary(S2, LAge)
range <- S2 %>% summarise(range(LAge))
sex <- table(S2$LSex)
language <- table(S2$LMotherLanguage)
LStudyWork <- table(S2$LStudyWork)
LHearingKown <- table(S2$LHearingKown)
LHearingKind <- table(S2$LHearingKind)
LHearingImp <- table(S2$LHearingImp)
duration <- S2 %>% summarise(Tmean = mean(TIME_total, na.rm= TRUE),
                            min = min(TIME_total, na.rm= TRUE),
                            max = max(TIME_total, na.rm= TRUE))
capture.output(as.matrix(Age), as.matrix(range), sex, language, 
               LStudyWork, LHearingKown, LHearingKind, LHearingImp, as.matrix(duration), 
               file="output/Exp2_demographics.txt")
rm(Age, range, sex, language, LStudyWork, LHearingKown, LHearingKind, LHearingImp, duration)


## comments
write.csv(data.frame(S2$participant, S2$VPN_Code, S2$Anmerkungen, S2$InstructionsClear, S2$Strategy), file="output/Exp2_comments.txt")


# after Exp-Evaluation
Eval1 <- table(S2$Eval1)
Eval2 <- table(S2$Eval2)
Eval3 <- table(S2$Eval3)
Eval4 <- table(S2$Eval4)
Eval5 <- table(S2$Eval5)
Eval6 <- table(S2$Eval6)
Eval7 <- table(S2$Eval7)
Eval8 <- table(S2$Eval8)

label <- c("Im Alltag achte ich stets auf den Klang der Stimme einer Person.",                   # I always attend to the sound of voices in daily life
           "Es fiel mir äußerst schwer, die Stimmen zu bewerten.",                               # it was very hard to me to classify the voices
           "Bei den meisten Stimmen hatte ich gar keine Ahnung, was ich drücken sollte.",        # in many trials I had no idea which key to press
           "Ich habe die ganze Zeit aufmerksam zugehört.",                                       # I listened very attentively all the time
           "Oft habe ich einfach irgendetwas geklickt.",                                         # Most of the time I responded randomly
           "Ich fand dieses Hörexperiment äußerst interessant.",                                 # The listening experiment was very interesting.  
           "Ich habe in jedem Durchgang versucht, die Bewertung so gut wie möglich zu machen.",  # I tried my best in every trial.
           "Ich achte normalerweise gar nicht auf die Stimmen von Personen.")                    # Usually I don't listen to the sound of peoples voices at all. 


capture.output(label[1], Eval1, label[2],Eval2, label[3],Eval3,label[4], Eval4, label[5],Eval5, label[6], Eval6,label[7], Eval7, label[8], Eval8,file="output/Exp2_after_experiment_evaluation.txt")
rm(label, Eval1, Eval2, Eval3, Eval4, Eval5, Eval6, Eval7, Eval8)

#------------------------------------------------------------------------------------------------------------------#
#                                        Analysis of Trials of omission                                            #
#------------------------------------------------------------------------------------------------------------------#

#load the preprocessed raw data
load(file ="input/Exp2_raw_data.RData")

#check for the number of missing (indicated by RT == 3000)
missings_Adapt <-E2_Adapt %>%  group_by(Participant) %>% filter(RT == 3000) %>% summarise(N = length(Participant),
                                                                                          prop = N/224) 

missings_Bline <- E2_Bline %>%  group_by(Participant) %>% filter(RT == 3000) %>% summarise(N = length(Participant),
                                                                                           prop = N/112) 
capture.output(as.matrix(missings_Adapt), as.matrix(missings_Bline), file = "output/Exp2_omissions_summary.txt")

#remove omissions from the data
E2_Adapt <- E2_Adapt %>% filter(RT != 3000) # 20 removed
E2_Bline <- E2_Bline %>% filter(RT != 3000) # 20 removed

rm(missings_Bline, missings_Adapt)

#save datasets again
save(E2_Bline, E2_Adapt, file ="input/Exp2_without_omissions.RData")


## End of Script