##########################################################################
## File: 02_Exp2_data_analysis.R
## Data Analysis for Exp 2: Adaptation of Emotion - speaker identities
# author: Christine Nussbaum 
# date 03/2026

# clear directory
rm(list=ls())

#set working directory to current file
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))

# load required packages
library("tidyverse")
library(ez)
library(effectsize)
library(lme4)           # version 1.1-35.1
library(ggeffects)      # version 1.6.0
library(afex)           # version 1.3-1

# load relevant functions
source("functions/mySummary.R") 
source("functions/tracedEzOut.R")

#load the data
load(file ="input/Exp2_without_omissions.RData")


#### Meaning of Variables

##E2_Bline

# Participant           #individual participant code, generated by the system
# Duration              #stimulus duration in ms
# SpID                  #speaker identity: nf01 and nr03 are females, nm03 and nm04 are males
# Word                  #peudoword: w01 - /belam/ , w02 - /molen/ , w03 - /namil/ , w05 - /loman/ (w05 is renamed in w04 in the manuscript)
# tML                   #target morph level: 20- 80% proportion of anger in the voice
# SpSex                 #speaker sex: f = female, m = male 
# Resp                  #participants' response: 0 = fear, 1 = angery
# RT                    #reaction time in ms
# Stimulus              # presented stimulus

##E2_Adapt

# Participant           #individual participant code, generated by the system
# Duration              #stimulus duration in ms
# SpID                  #speaker identity: nf01 and nf03 are females, nm03 and nm04 are males
# Word                  #peudoword: w01 - /belam/ , w02 - /molen/ , w03 - /namil/ , w05 - /loman/ (w05 is renamed in w04 in the manuscript)
# tML                   #target morph level: 20- 80% proportion of anger in the voice
# SpSex                 #speaker sex: f = female, m = male 
# Resp                  #participants' response: 0 = fear, 1 = angry
# RT                    #reaction time in ms
# AdaptType             #Adaptation Condition
# Blockorder            #1 of 4 possible block orders
# Stimulus              #presented stimulus



#-------------------------------------------------------------------------------#
#                  Analysis 1: logistic regression                              #
#-------------------------------------------------------------------------------#
## declare tML as numerical variable
E2_Adapt$tML <- as.numeric(as.character(E2_Adapt$tML))

#scale tML, because this is recommended for mixed-effects modelling
E2_Adapt$tML_sc <- scale(E2_Adapt$tML)


#create separate datasets for female and male voices
E2_Adapt_f <- E2_Adapt %>% filter(SpSex == "f")
E2_Adapt_m <- E2_Adapt %>% filter(SpSex == "m")

#-------------------------------------------------------------------------------#
#                         1a:  female voices  only                              #
#-------------------------------------------------------------------------------#
# outcome: Resp
# predictors: ML,  SpID, AdaptType
# random: Participant

#------------------------------------------------------------------------
# Step1: estimating the model 

# m: assumed fixed effects structure for Participant 
m <- glmer(Resp ~ tML_sc * SpID * AdaptType   + (1 | Participant), data = E2_Adapt_f, family = binomial,
           control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5))) # it was recommended to try out different optimizers to avoid converging failure and this worked


#------------------------------------------------------------------------
# Step2: calculating the p-values of the effects with afex
m_test<- mixed(m, data = E2_Adapt_f, method = "LRT", family = "binomial") # takes a few minutes
m_test

# Model: Resp ~ tML_sc * SpID * AdaptType + (1 | Participant)
# Data: E2_Adapt_f
# Df full model: 9
# Effect df       Chisq p.value
# 1                tML_sc  1 1785.96 ***   <.001
# 2                  SpID  1   44.00 ***   <.001
# 3             AdaptType  1     7.16 **    .007
# 4           tML_sc:SpID  1   34.14 ***   <.001
# 5      tML_sc:AdaptType  1      5.95 *    .015
# 6        SpID:AdaptType  1     7.21 **    .007
# 7 tML_sc:SpID:AdaptType  1        0.40    .528

summary(m)

###########################################################################
# Generalized linear mixed model fit by maximum likelihood (Laplace Approximation) ['glmerMod']
# Family: binomial  ( logit )
# Formula: Resp ~ tML_sc * SpID * AdaptType + (1 | Participant)
# Data: E2_Adapt_f
# Control: glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 2e+05))
# 
# AIC       BIC    logLik -2*log(L)  df.resid 
# 4459.9    4517.9   -2220.9    4441.9      4668 
# 
# Scaled residuals: 
#   Min      1Q  Median      3Q     Max 
# -6.1790 -0.5361 -0.2245  0.5463  5.9540 
# 
# Random effects:
#   Groups      Name        Variance Std.Dev.
# Participant (Intercept) 0.4097   0.6401  
# Number of obs: 4677, groups:  Participant, 42
# 
# Fixed effects:
#   Estimate Std. Error z value Pr(>|z|)    
#   (Intercept)                          -0.1673653  0.1249952  -1.339 0.180579    
#   tML_sc                                1.7435683  0.0954688  18.263  < 2e-16 ***
#   SpIDf2                               -0.3030417  0.1049771  -2.887 0.003893 ** 
#   AdaptTypef1_fea/f2_ang                0.0007905  0.1114026   0.007 0.994339    
#   tML_sc:SpIDf2                        -0.4761197  0.1235413  -3.854 0.000116 ***
#   tML_sc:AdaptTypef1_fea/f2_ang         0.2828652  0.1416886   1.996 0.045892 *  
#   SpIDf2:AdaptTypef1_fea/f2_ang        -0.4137335  0.1542117  -2.683 0.007299 ** 
#   tML_sc:SpIDf2:AdaptTypef1_fea/f2_ang -0.1166325  0.1846938  -0.631 0.527719     
###########################################################################

# save models as R objects
save(m, m_test, file= "input/E2_GLMs_female.RData")


# capture output of model "m" 
capture.output(summary(m), m_test, file= "output/Exp2_GLMM_female.txt")

# extract fitted values
E2_Adapt_f$fitted <- fitted(m)

#aggregate values of fitted
GLM_fit <- mySummary(E2_Adapt_f, fitted, Participant, SpID, AdaptType)
GLM_descriptive <- mySummary(GLM_fit, fitted, SpID, AdaptType)
capture.output(GLM_descriptive, file= "output/Exp2_GLMM_female_descriptive.txt")


#-------------------------------------------------------------------------------#
#                          1b:  male voices  only                               #
#-------------------------------------------------------------------------------#

# outcome: Resp
# predictors: ML,  SpID, AdaptType
# random: Participant

#------------------------------------------------------------------------
# Step1: estimating the model 


# m: assumed fixed effects structure for Participant 
m <- glmer(Resp ~ tML_sc * SpID * AdaptType   + (1 | Participant), data = E2_Adapt_m, family = binomial,
           control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5))) # it was recommended to try out different optimizers to avoid converging failure and this worked

#------------------------------------------------------------------------
# Step2: calculating the p-values of the effects with afex
m_test<- mixed(m, data = E2_Adapt_m, method = "LRT", family = "binomial") # takes a few minutes
m_test

# Model: Resp ~ tML_sc * SpID * AdaptType + (1 | Participant)
# Data: E2_Adapt_m
# Df full model: 9
# Effect df       Chisq p.value
# 1                tML_sc  1 1860.19 ***   <.001
# 2                  SpID  1  441.93 ***   <.001
# 3             AdaptType  1   34.59 ***   <.001
# 4           tML_sc:SpID  1   57.57 ***   <.001
# 5      tML_sc:AdaptType  1        2.61    .106
# 6        SpID:AdaptType  1        0.48    .490
# 7 tML_sc:SpID:AdaptType  1        0.85    .357

summary(m)

###########################################################################
# Generalized linear mixed model fit by maximum likelihood (Laplace Approximation) ['glmerMod']
# Family: binomial  ( logit )
# Formula: Resp ~ tML_sc * SpID * AdaptType + (1 | Participant)
# Data: E2_Adapt_m
# Control: glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 2e+05))
# 
# AIC       BIC    logLik -2*log(L)  df.resid 
# 3815.8    3873.9   -1898.9    3797.8      4673 
# 
# Scaled residuals: 
#   Min      1Q  Median      3Q     Max 
# -8.6018 -0.4417 -0.1830  0.3915  8.7626 
# 
# Random effects:
#   Groups      Name        Variance Std.Dev.
# Participant (Intercept) 0.6485   0.8053  
# Number of obs: 4682, groups:  Participant, 42
# 
# Fixed effects:
#   Estimate Std. Error z value Pr(>|z|)    
#   (Intercept)                          -1.37638    0.15394  -8.941  < 2e-16 ***
#   tML_sc                                1.49707    0.09676  15.473  < 2e-16 ***
#   SpIDm4                                1.87960    0.12822  14.660  < 2e-16 ***
#   AdaptTypem3_fea/m4_ang               -0.46952    0.13559  -3.463 0.000535 ***
#   tML_sc:SpIDm4                         0.91720    0.15639   5.865  4.5e-09 ***
#   tML_sc:AdaptTypem3_fea/m4_ang        -0.07507    0.14053  -0.534 0.593235    
#   SpIDm4:AdaptTypem3_fea/m4_ang        -0.12610    0.18235  -0.691 0.489258    
#   tML_sc:SpIDm4:AdaptTypem3_fea/m4_ang -0.19879    0.21619  -0.919 0.357841      
###########################################################################

# save models as R objects
save(m, m_test, file= "input/E2_GLMs_male.RData")


# capture output of model "m" 
capture.output(summary(m), m_test, file= "output/Exp2_GLMM_male.txt")


# extract fitted values
E2_Adapt_m$fitted <- fitted(m)

#aggregate values of fitted
GLM_fit <- mySummary(E2_Adapt_m, fitted, Participant, SpID, AdaptType)
GLM_descriptive <- mySummary(GLM_fit, fitted, SpID, AdaptType)
capture.output(GLM_descriptive, file= "output/Exp2_GLMM_male_descriptive.txt")


#-------------------------------------------------------------------------------#
#   Analysis 2: The amount of classifications (averaged across tML)             #
#-------------------------------------------------------------------------------#

#aggregate across pseudoword, speaker and tML for analysis
E2_Resp_f <- mySummary(E2_Adapt_f, Resp, Participant, SpID, SpSex, AdaptType) #does not contain Baseline
E2_Resp_m <- mySummary(E2_Adapt_m, Resp, Participant, SpID, SpSex, AdaptType) #does not contain Baseline


#-------------------------------------------------------------------------------#
#                         2a:  female voices  only                              #
#-------------------------------------------------------------------------------#

##########################################################################
## ANOVA IIa: 2 x 2 within subject (female voices only)
# data: E2_Resp_f
# dv: Resp
# wid: Participant
# within: AdaptType, SpID

a<-ezANOVA(data=E2_Resp_f, dv=.(Resp), wid=.(Participant), within = .(AdaptType, SpID), type=3, detailed = TRUE)
b = tracedEzOut(a, print = TRUE, sph.cor = "HF", mau.p = 0.05, etasq = "partial", dfsep = ", ")

#N= 42 entered Analysis
##############################################################################
# Effect                                     Text
# 1    (Intercept) F(1, 41) = 730.703, p < .001, np2 = .947
# 2      AdaptType F(1, 41) =   4.384, p = .043, np2 = .097
# 3           SpID F(1, 41) =  16.260, p < .001, np2 = .284
# 4 AdaptType:SpID F(1, 41) =  12.826, p = .001, np2 = .238 -> replicates the GLMM, not reported in the manuscript
##############################################################################

capture.output(b, file= "output/Exp2_Resp_ANOVAIIa_females.txt")

# visualize data (just to check)
ezPlot(data=E2_Resp_f, dv=.(Resp), wid=.(Participant), within = .(AdaptType, SpID), x=SpID, split=AdaptType)


########################### Post - Hoc Analysis ###########################################################

########################################################################################
### Post-Hoc Analysis: Interaction of AdaptType und SpID, also including the Baseline
########################################################################################

#aggregate Data (in this case not really necessary)
PH1 <- E2_Resp_f %>% group_by(Participant, SpID, AdaptType) %>% summarise(Resp = mean(Resp))

#get descriptive data 
PH1_descriptive <- mySummary(PH1, Resp, SpID, AdaptType)

#convert partly into wide format
PH1 <- spread(PH1, AdaptType, Resp)

###separate per speaker sex
PH1f1<- PH1 %>% filter(SpID == "f1")
PH1f2<- PH1 %>% filter(SpID == "f2")


###now we add the Baseline information 
E2_Bline_Resp <- mySummary(E2_Bline[E2_Bline$SpSex == "f",], Resp, Participant, SpID) 
E2_Bline_Resp <- E2_Bline_Resp %>% rename(Baseline = Resp)
Baseline_descriptive <- mySummary(E2_Bline_Resp, Baseline, SpID)


Blinef1<- E2_Bline_Resp[,1:3] %>% filter(SpID == "f1")
PH1f1 <- merge(PH1f1, Blinef1)

Blinef2<- E2_Bline_Resp[,1:3] %>% filter(SpID == "f2")
PH1f2 <- merge(PH1f2, Blinef2)

rm(E1_Bline_Resp, Blinef, Blinem)


### t-tests, separately for each SpID

names(PH1f1)

#F1: 
AdaptTypef1 <- t.test(PH1f1$`f1_ang/f2_fea`, PH1f1$`f1_fea/f2_ang`, paired = TRUE)
d_AdaptTypef1 <- t_to_d(AdaptTypef1$statistic, AdaptTypef1$parameter, paired = TRUE)


##################################################
# data:  PH1f1$`f1_ang/f2_fea` and PH1f1$`f1_fea/f2_ang`
# t = -0.09238, df = 41, p-value = 0.9268
# alternative hypothesis: true mean difference is not equal to 0
# 95 percent confidence interval:
#   -0.03722904  0.03397207
# sample estimates:
#   mean difference 
# -0.001628486  


AdaptBasef1 <- t.test(PH1f1$Baseline, PH1f1$`f1_ang/f2_fea`, paired = TRUE)
d_AdaptBasef1 <- t_to_d(AdaptBasef1$statistic, AdaptBasef1$parameter, paired = TRUE)

##################################################
# data:  PH1f1$Baseline and PH1f1$`f1_ang/f2_fea`
# t = 0.63857, df = 41, p-value = 0.5267
# alternative hypothesis: true mean difference is not equal to 0
# 95 percent confidence interval:
#   -0.02712308  0.05220691
# sample estimates:
#   mean difference 
# 0.01254191 

AdaptBasef1b <- t.test(PH1f1$Baseline, PH1f1$`f1_fea/f2_ang`, paired = TRUE)
d_AdaptBasef1b <- t_to_d(AdaptBasef1b$statistic, AdaptBasef1b$parameter, paired = TRUE)

##################################################
# data:  PH1f1$Baseline and PH1f1$`f1_fea/f2_ang`
# t = 0.66249, df = 41, p-value = 0.5114
# alternative hypothesis: true mean difference is not equal to 0
# 95 percent confidence interval:
#   -0.02235509  0.04418194
# sample estimates:
#   mean difference 
# 0.01091343 

#F2: 

AdaptTypef2 <- t.test(PH1f2$`f1_ang/f2_fea`, PH1f2$`f1_fea/f2_ang`, paired = TRUE)
d_AdaptTypef2 <- t_to_d(AdaptTypef2$statistic, AdaptTypef2$parameter, paired = TRUE)


##################################################
# data:  PH1f2$`f1_ang/f2_fea` and PH1f2$`f1_fea/f2_ang`
# t = 3.7954, df = 41, p-value = 0.0004781
# alternative hypothesis: true mean difference is not equal to 0
# 95 percent confidence interval:
#   0.02919696 0.09560274
# sample estimates:
#   mean difference 
# 0.06239985 



AdaptBasef2 <- t.test(PH1f2$Baseline, PH1f2$`f1_ang/f2_fea`, paired = TRUE)
d_AdaptBasef2 <- t_to_d(AdaptBasef2$statistic, AdaptBasef2$parameter, paired = TRUE)

##################################################
# data:  PH1f2$Baseline and PH1f2$`f1_ang/f2_fea`
# t = -2.583, df = 41, p-value = 0.01346
# alternative hypothesis: true mean difference is not equal to 0
# 95 percent confidence interval:
#   -0.09447691 -0.01156685
# sample estimates:
#   mean difference 
# -0.05302188 

AdaptBasef2b <- t.test(PH1f2$Baseline, PH1f2$`f1_fea/f2_ang`, paired = TRUE)
d_AdaptBasef2b <- t_to_d(AdaptBasef2b$statistic, AdaptBasef2b$parameter, paired = TRUE)

##################################################
# data:  PH1f2$Baseline and PH1f2$`f1_fea/f2_ang`
# t = 0.49167, df = 41, p-value = 0.6256
# alternative hypothesis: true mean difference is not equal to 0
# 95 percent confidence interval:
#   -0.02914196  0.04789790
# sample estimates:
#   mean difference 
# 0.009377968



#save results
capture.output(as.matrix(PH1_descriptive), as.matrix(Baseline_descriptive),
               AdaptTypef1, d_AdaptTypef1, AdaptTypef2, d_AdaptTypef2,
               AdaptBasef1, d_AdaptBasef1,AdaptBasef1b,d_AdaptBasef1b,
               AdaptBasef2, d_AdaptBasef2,AdaptBasef2b,d_AdaptBasef2b,
               file = "output/Exp2_Resp_post-hoc_females.txt")

#keep environment tidy
rm(PH1, PH1_descriptive, PH1f1, PH1f2, AdaptTypef1, d_AdaptTypef1, AdaptTypef2, d_AdaptTypef2,
   AdaptBasef1, d_AdaptBasef1,AdaptBasef1b,d_AdaptBasef1b,
   AdaptBasef2, d_AdaptBasef2,AdaptBasef2b,d_AdaptBasef2b)



#-------------------------------------------------------------------------------#
#                         2b:  male voices  only                              #
#-------------------------------------------------------------------------------#

##########################################################################
## ANOVA IIa: 2 x 2 within subject (female voices only)
# data: E2_Resp_m
# dv: Resp
# wid: Participant
# within: AdaptType, SpID

a<-ezANOVA(data=E2_Resp_m, dv=.(Resp), wid=.(Participant), within = .(AdaptType, SpID), type=3, detailed = TRUE)
b = tracedEzOut(a, print = TRUE, sph.cor = "HF", mau.p = 0.05, etasq = "partial", dfsep = ", ")

#N= 42 entered Analysis
##############################################################################
# Effect                                     Text
# 1    (Intercept) F(1, 41) = 600.322, p < .001, np2 = .936
# 2      AdaptType F(1, 41) =  21.455, p < .001, np2 = .344
# 3           SpID F(1, 41) = 251.723, p < .001, np2 = .860
# 4 AdaptType:SpID F(1, 41) =   0.003, p = .959, np2 < .010 -> replicates the GLMM, not reported in the manuscript
##############################################################################

capture.output(b, file= "output/Exp2_Resp_ANOVAIIb_males.txt")

# visualize data (just to check)
ezPlot(data=E2_Resp_m, dv=.(Resp), wid=.(Participant), within = .(AdaptType, SpID), x=SpID, split=AdaptType)


########################### Post - Hoc Analysis ###########################################################

########################################################################################
### Post-Hoc Analysis: Interaction of AdaptType und SpID, also including the Baseline
########################################################################################

#aggregate Data (in this case not really necessary)
PH2 <- E2_Resp_m %>% group_by(Participant, SpID, AdaptType) %>% summarise(Resp = mean(Resp))

#get descriptive data 
PH2_descriptive <- mySummary(PH2, Resp, SpID, AdaptType)

#convert partly into wide format
PH2 <- spread(PH2, AdaptType, Resp)

###separate per speaker sex
PH2m3<- PH2 %>% filter(SpID == "m3")
PH2m4<- PH2 %>% filter(SpID == "m4")


###now we add the Baseline information 
E2_Bline_Resp <- mySummary(E2_Bline[E2_Bline$SpSex == "m",], Resp, Participant, SpID) 
E2_Bline_Resp <- E2_Bline_Resp %>% rename(Baseline = Resp)
Baseline_descriptive <- mySummary(E2_Bline_Resp, Baseline, SpID)


Blinem3<- E2_Bline_Resp[,1:3] %>% filter(SpID == "m3")
PH2m3 <- merge(PH2m3, Blinem3)

Blinem4<- E2_Bline_Resp[,1:3] %>% filter(SpID == "m4")
PH2m4 <- merge(PH2m4, Blinem4)

rm(E2_Bline_Resp, Blinem3, Blinem4)


### t-tests, separately for each SpID



#m3: 
AdaptTypem3 <- t.test(PH2m3$`m3_ang/m4_fea`, PH2m3$`m3_fea/m4_ang`, paired = TRUE)
d_AdaptTypem3 <- t_to_d(AdaptTypem3$statistic, AdaptTypem3$parameter, paired = TRUE)


##################################################
# data:  PH2m3$`m3_ang/m4_fea` and PH2m3$`m3_fea/m4_ang`
# t = 3.8105, df = 41, p-value = 0.000457
# alternative hypothesis: true mean difference is not equal to 0
# 95 percent confidence interval:
#   0.03228111 0.10508153
# sample estimates:
#   mean difference 
# 0.06868132 


AdaptBasem3 <- t.test(PH2m3$Baseline, PH2m3$`m3_ang/m4_fea`, paired = TRUE)
d_AdaptBasem3 <- t_to_d(AdaptBasem3$statistic, AdaptBasem3$parameter, paired = TRUE)

##################################################
# data:  PH2m3$Baseline and PH2m3$`m3_ang/m4_fea`
# t = -0.82721, df = 41, p-value = 0.4129
# alternative hypothesis: true mean difference is not equal to 0
# 95 percent confidence interval:
#   -0.04805568  0.02012770
# sample estimates:
#   mean difference 
# -0.01396399 

AdaptBasem3b <- t.test(PH2m3$Baseline, PH2m3$`m3_fea/m4_ang`, paired = TRUE)
d_AdaptBasem3b <- t_to_d(AdaptBasem3b$statistic, AdaptBasem3b$parameter, paired = TRUE)

##################################################
# data:  PH2m3$Baseline and PH2m3$`m3_fea/m4_ang`
# t = 2.9022, df = 41, p-value = 0.005939
# alternative hypothesis: true mean difference is not equal to 0
# 95 percent confidence interval:
#   0.01664090 0.09279375
# sample estimates:
#   mean difference 
# 0.05471733 

#m4: 

AdaptTypem4 <- t.test(PH2m4$`m3_ang/m4_fea`, PH2m4$`m3_fea/m4_ang`, paired = TRUE)
d_AdaptTypem4 <- t_to_d(AdaptTypem4$statistic, AdaptTypem4$parameter, paired = TRUE)


##################################################
# data:  PH2m4$`m3_ang/m4_fea` and PH2m4$`m3_fea/m4_ang`
# t = 4.2366, df = 41, p-value = 0.0001253
# alternative hypothesis: true mean difference is not equal to 0
# 95 percent confidence interval:
#   0.03640784 0.10273785
# sample estimates:
#   mean difference 
# 0.06957284 
##################################################


AdaptBasem4 <- t.test(PH2m4$Baseline, PH2m4$`m3_ang/m4_fea`, paired = TRUE)
d_AdaptBasem4 <- t_to_d(AdaptBasem4$statistic, AdaptBasem4$parameter, paired = TRUE)

##################################################
# data:  PH2m4$Baseline and PH2m4$`m3_ang/m4_fea`
# t = -0.1372, df = 41, p-value = 0.8915
# alternative hypothesis: true mean difference is not equal to 0
# 95 percent confidence interval:
#   -0.03328500  0.02905025
# sample estimates:
#   mean difference 
# -0.002117371  

AdaptBasem4b <- t.test(PH2m4$Baseline, PH2m4$`m3_fea/m4_ang`, paired = TRUE)
d_AdaptBasem4b <- t_to_d(AdaptBasem4b$statistic, AdaptBasem4b$parameter, paired = TRUE)

##################################################
# data:  PH2m4$Baseline and PH2m4$`m3_fea/m4_ang`
# t = 3.4471, df = 41, p-value = 0.001323
# alternative hypothesis: true mean difference is not equal to 0
# 95 percent confidence interval:
#   0.02793544 0.10697550
# sample estimates:
#   mean difference 
# 0.06745547 



#save results
capture.output(as.matrix(PH2_descriptive), as.matrix(Baseline_descriptive),
               AdaptTypem3, d_AdaptTypem3, AdaptTypem4, d_AdaptTypem4,
               AdaptBasem3, d_AdaptBasem3,AdaptBasem3b,d_AdaptBasem3b,
               AdaptBasem4, d_AdaptBasem4,AdaptBasem4b,d_AdaptBasem4b,
               file = "output/Exp2_Resp_post-hoc_males.txt")

#keep environment tidy
rm(PH2, PH2_descriptive, PH2m3, PH2m4, AdaptTypem3, d_AdaptTypem3, AdaptTypem4, d_AdaptTypem4,
   AdaptBasem3, d_AdaptBasem3,AdaptBasem3b,d_AdaptBasem3b,
   AdaptBasem4, d_AdaptBasem4,AdaptBasem4b,d_AdaptBasem4b)




##End of Script